### ISSUE TITLE
Transfer to @rust-windowing

### ISSUE THREAD

**Issue by madsmtm** [norse-rs/raw-window-metal#16]
@msiglreith seems to not have the time to maintain this any more (if I understood correctly?), so we should transfer this to the @rust-windowing organization. This was [agreed on](https://hackmd.io/_YK76P6-TQq2Rw3s3Y3y_g#Moving-raw-window-metal-to-rust-windowing) at the previous Winit meeting.

Tasks:
- [x] Move repository.
- [x] Transfer crate ownership on crates.io to `madsmtm`, `daxpedda` and `kchibisov`.
- [x] Create a team @rust-windowing/raw-window-metal, and add that as publisher on crates.io.

**Comment by msiglreith** [comment]
thanks, transfer should be complete
minor point: some readme links are referring to `norse-rs`

**Comment by madsmtm** [comment]
Wonderful, thanks!

(And thanks for your contributions over the years to Winit and the rest of the ecosystem, wish you well in your current/future endeavours, whatever those may be ;) )
